# This is a basic workflow to help you get started with Actions

name: COVID Data Scraper

# Controls when the workflow will run
on:
  schedule:
    - cron:  '00 16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: execute scraper py script # run mohscraper.py to get the latest data
        working-directory: ./scraper
        run: python3 mohscraper.py
      
      - name: execute api py script # run mohscraper.py to get the latest data
        working-directory: ./scripts
        run: python3 createLatest.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add -A
          git commit -m "daily update data"
          git push
      
      
          


        


